### ISSUE TITLE
latest release seems to be broken

### ISSUE THREAD

**Issue by areel** [editor-framework/generator#1]
I successfully used yo editor-framework last week to create a new project.

Creating another project today does not produce a working project.

using gulp run fails stating that ./editor-framework/init is not available.

comparing projects, seems a lot has been changed since I last created.

**Comment by jwu** [comment]
Hi areal,

I'm woking on the v0.4.0 and it changes a lot. I think I've update the document and CHANGELOG.md to notify the changes.
